web:
  build: .
  command: 'bash -c ''npm install; node app.js'''
  volumes:
   - ./:/app/user/
   - /app/user/node_modules
  working_dir: /app/user
  environment:
    PORT: 8086
  ports:
    - '8086:8086'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8085
  ports:
    - '8085:8085'
  volumes:
    - '.:/app/user'
